INCLUDE "driver/inc/macro.asm"
PUSHS
INCLUDE "driver/inc/memory.asm"
POPS
; =============== MAIN ===============
INCLUDE "driver/driver.asm"
INCLUDE "driver/sfx/sfx_none.asm"
INCLUDE "driver/data/frequencies.asm"
INCLUDE "driver/data/song_list.asm"
INCLUDE "driver/data/waves.asm"
INCLUDE "driver/data/frequencies_noise.asm"
; =============== BACKGROUND MUSIC ===============
INCLUDE "driver/bgm/bgm_title.asm"
INCLUDE "driver/bgm/bgm_stage_select.asm"
INCLUDE "driver/bgm/bgm_stage_start.asm"
INCLUDE "driver/bgm/bgm_password.asm"
INCLUDE "driver/bgm/bgm_boss.asm"
INCLUDE "driver/bgm/bgm_stage_clear.asm"
INCLUDE "driver/bgm/bgm_weaponget.asm"
INCLUDE "driver/bgm/bgm_crashman.asm"
INCLUDE "driver/bgm/bgm_airman.asm"
INCLUDE "driver/bgm/bgm_metalman.asm"
INCLUDE "driver/bgm/bgm_hardman.asm"
INCLUDE "driver/bgm/bgm_woodman.asm"
INCLUDE "driver/bgm/bgm_topman.asm"
INCLUDE "driver/bgm/bgm_magnetman.asm"
INCLUDE "driver/bgm/bgm_needleman.asm"
INCLUDE "driver/bgm/bgm_wily_intro.asm"
INCLUDE "driver/bgm/bgm_wily_castle.asm"
INCLUDE "driver/bgm/bgm_ending.asm"
INCLUDE "driver/bgm/bgm_unused_ending.asm"
INCLUDE "driver/bgm/bgm_silence.asm"
; ==============================
INCLUDE "driver/data/sfx_priority.asm"
; =============== SOUND EFFECTS ===============
INCLUDE "driver/sfx/sfx_land.asm"
INCLUDE "driver/sfx/sfx_shoot.asm"
INCLUDE "driver/sfx/sfx_enemy_hit.asm"
INCLUDE "driver/sfx/sfx_enemy_dead.asm"
INCLUDE "driver/sfx/sfx_deflect.asm"
INCLUDE "driver/sfx/sfx_explode.asm"
INCLUDE "driver/sfx/sfx_bar.asm"
INCLUDE "driver/sfx/sfx_etank.asm"
INCLUDE "driver/sfx/sfx_1up.asm"
INCLUDE "driver/sfx/sfx_shutter.asm"
INCLUDE "driver/sfx/sfx_boss_bar.asm"
INCLUDE "driver/sfx/sfx_teleport_in.asm"
INCLUDE "driver/sfx/sfx_teleport_out.asm"
INCLUDE "driver/sfx/sfx_freeze_toggle.asm"
INCLUDE "driver/sfx/sfx_weapon_absorb.asm"
INCLUDE "driver/sfx/sfx_block.asm"
INCLUDE "driver/sfx/sfx_ufo_crash.asm"
INCLUDE "driver/sfx/sfx_cursor_move.asm"
INCLUDE "driver/sfx/sfx_damaged.asm"
INCLUDE "driver/sfx/sfx_unused2.asm"
INCLUDE "driver/sfx/sfx_silence.asm"