GFX_CrashMan: INCBIN "data/game/act/boss/crashman/crashman_gfx.bin"
GFX_ActLvlMetal: INCBIN "data/game/lvl/metal/act_gfx.bin"
GFX_MetalMan: INCBIN "data/game/act/boss/metalman/metalman_gfx.bin"
GFX_ActLvlWood: INCBIN "data/game/lvl/wood/act_gfx.bin"
GFX_WoodMan: INCBIN "data/game/act/boss/woodman/woodman_gfx.bin"
GFX_ActLvlAir: INCBIN "data/game/lvl/air/act_gfx.bin"
GFX_AirMan: INCBIN "data/game/act/boss/airman/airman_gfx.bin"
GFX_SmallFont: INCBIN "data/font/smallfont_gfx.bin"
	mIncJunk "L097A00"
GFX_LvlHard: INCBIN "data/game/lvl/hard/bg_gfx.bin"
