GFX_WilyCastle: INCBIN "data/scene/castle/wilycastle_gfx.bin"
GFX_WilyStation: INCBIN "data/scene/station/wilystation_gfx.bin"
GFX_Space: INCBIN "data/scene/_space/space_gfx.bin"
GFX_SpaceOBJ: INCBIN "data/scene/_space/space_obj_gfx.bin"
GFX_HardMan: INCBIN "data/game/act/boss/hardman/hardman_gfx.bin"
GFX_TopMan: INCBIN "data/game/act/boss/topman/topman_gfx.bin"
