TilemapDef_Title: INCLUDE "data/title/title_bg.asm"
	mIncJunk "L0440FE"
TilemapDef_StageSel: INCLUDE "data/stagesel/stagesel_bg.asm"
	mIncJunk "L04512D"
TilemapDef_GetWpn: INCLUDE "data/getwpn/getwpn_bg.asm"
	mIncJunk "L0453B9"
TilemapDef_WilyCastle: INCLUDE "data/scene/castle/wilycastle_bg.asm"
	mIncJunk "L045513"
TilemapDef_WilyStation: INCLUDE "data/scene/station/wilystation_bg.asm"
	mIncJunk "L0456DF"
