GFX_ActLvlHard: INCBIN "data/lvl/hard/act_gfx.bin"
GFX_Bikky: INCBIN "data/act/bikky/bikky_gfx.bin"
GFX_ActLvlTop: INCBIN "data/lvl/top/act_gfx.bin"
GFX_ActLvlMagnet: INCBIN "data/lvl/magnet/act_gfx.bin"
GFX_MagnetMan: INCBIN "data/act/magnetman/magnetman_gfx.bin"
GFX_ActLvlNeedle: INCBIN "data/lvl/needle/act_gfx.bin"
GFX_NeedleMan: INCBIN "data/act/needleman/needleman_gfx.bin"
GFX_ActLvlCrash: INCBIN "data/lvl/crash/act_gfx.bin"
