; =============== WEAPON PLAYER CONTROLS ===============
INCLUDE "data/game/wpn/ctrl_run.asm"
INCLUDE "data/game/wpn/p/ctrl.asm"
INCLUDE "data/game/wpn/rc/ctrl.asm"
INCLUDE "data/game/wpn/rm/ctrl.asm"
INCLUDE "data/game/wpn/rj/ctrl.asm"
INCLUDE "data/game/wpn/sg/ctrl.asm"
INCLUDE "data/game/wpn/helperctrl_sub.asm"
INCLUDE "data/game/wpn/tp/ctrl.asm"
INCLUDE "data/game/wpn/ar/ctrl.asm"
INCLUDE "data/game/wpn/wd/ctrl.asm"
INCLUDE "data/game/wpn/me/ctrl.asm"
INCLUDE "data/game/wpn/cr/ctrl.asm"
INCLUDE "data/game/wpn/ne/ctrl.asm"
INCLUDE "data/game/wpn/ha/ctrl.asm"
INCLUDE "data/game/wpn/mg/ctrl.asm"
; =============== WEAPON SHOT CODE ===============
INCLUDE "data/game/wpn/shot_run.asm"
INCLUDE "data/game/wpn/p/shot.asm"
INCLUDE "data/game/wpn/tp/shot.asm"
INCLUDE "data/game/wpn/ar/shot.asm"
INCLUDE "data/game/wpn/wd/shot.asm"
INCLUDE "data/game/wpn/me/shot.asm"
INCLUDE "data/game/wpn/cr/shot.asm"
INCLUDE "data/game/wpn/ne/shot.asm"
INCLUDE "data/game/wpn/ha/shot.asm"
INCLUDE "data/game/wpn/mg/shot.asm"
; =============== SHOT SPRITE MAPPINGS ===============
INCLUDE "data/game/wpn/p/p_spr.asm"
INCLUDE "data/game/wpn/tp/tp_spr.asm"
INCLUDE "data/game/wpn/ar/ar_spr.asm"
INCLUDE "data/game/wpn/wd/wd_spr.asm"
INCLUDE "data/game/wpn/me/me_spr.asm"
INCLUDE "data/game/wpn/cr/cr_spr.asm"
INCLUDE "data/game/wpn/ne/ne_spr.asm"
INCLUDE "data/game/wpn/ha/ha_spr.asm"
INCLUDE "data/game/wpn/mg/mg_spr.asm"
INCLUDE "data/game/wpn/sg/sg_spr.asm"
; =============== SHOT DATA ===============
INCLUDE "data/game/wpn/me/pos_tbl.asm"
INCLUDE "data/game/wpn/wd/pos_tbl.asm"
INCLUDE "data/game/wpn/prop_tbl.asm"
; =============== PASSWORD INPUT/VIEW ===============
INCLUDE "data/password/password.asm"
INCLUDE "data/password/password_tbl.asm"
INCLUDE "data/password/password_ev.asm"
INCLUDE "data/password/passwordview.asm"
INCLUDE "data/password/passwordview_ev.asm"
; =============== GAMEPLAY CHEATS ===============
INCLUDE "data/game/cheat.asm"
; =============== CUTSCENES ===============
INCLUDE "data/scene/station/wilystation.asm"
INCLUDE "data/scene/ending/ending.asm"
INCLUDE "data/scene/credits/credits.asm"
INCLUDE "data/scene/sub.asm"
; =============== CUTSCENE BACKGROUNDS ===============
TilemapDef_WilyStationEntrance: INCLUDE "data/scene/_space/entrance_bg.asm"
TilemapDef_Earth: 				INCLUDE "data/scene/ending/earth_bg.asm"
TilemapDef_Ending_Space: 		INCLUDE "data/scene/ending/ending_space_bg.asm"
TilemapDef_Credits_Space: 		INCLUDE "data/scene/credits/space_bg.asm"
	mIncJunk "L016166"
SETCHARMAP credits
TilemapDef_Credits_Thank:		INCLUDE "data/scene/credits/thank_bg.asm"
Credits_StarfieldSprTbl:		INCLUDE "data/scene/credits/starfield_dspr.asm"
; =============== CUTSCENE SPRITE MAPPINGS ===============
INCLUDE "data/scene/spr_ptr.asm"
INCLUDE "data/scene/_space/spr/null_spr.asm"
INCLUDE "data/scene/_space/spr/wily_sm_spr.asm"
INCLUDE "data/scene/_space/spr/pl_spr.asm"
INCLUDE "data/scene/_space/spr/wily_spr.asm"
INCLUDE "data/scene/_space/spr/missile_spr.asm"
INCLUDE "data/scene/_space/spr/skulljaw_spr.asm"
INCLUDE "data/scene/_space/spr/wilycrash_spr.asm"
INCLUDE "data/scene/_space/spr/wilynuke_spr.asm"
INCLUDE "data/scene/_space/spr/expl_spr.asm"
INCLUDE "data/scene/credits/pl_spr.asm"

; =============== CAST ROLL DATA ===============
INCLUDE "data/scene/credits/credits_tbl.asm"

; =============== CAST ROLL SPRITE MAPPINGS ===============
;
; [POI] There are unused sprite mappings for some of the larger enemies.
;       They didn't make the cut as there wouldn't be enough space in OAM to display
;       them, their name and the large Rockman sprite at the same time.
;
;       None of them have entries or names in the cast roll, just unreferenced sprites.
;
INCLUDE "data/scene/credits/cast_spr/bee_spr.asm"
INCLUDE "data/scene/credits/cast_spr/chibee_spr.asm"
INCLUDE "data/scene/credits/cast_spr/wanaan_spr.asm"
INCLUDE "data/scene/credits/cast_spr/hammerjoe_spr.asm"
INCLUDE "data/scene/credits/cast_spr/neomonking_spr.asm"
INCLUDE "data/scene/credits/cast_spr/neomet_spr.asm"
INCLUDE "data/scene/credits/cast_spr/unused_pickelmanbull_spr.asm"
INCLUDE "data/scene/credits/cast_spr/unused_bikky_spr.asm"
INCLUDE "data/scene/credits/cast_spr/komasaburo_spr.asm"
INCLUDE "data/scene/credits/cast_spr/mechakkero_spr.asm"
INCLUDE "data/scene/credits/cast_spr/magfly_spr.asm"
INCLUDE "data/scene/credits/cast_spr/giantspringer_spr.asm"
INCLUDE "data/scene/credits/cast_spr/peterchy_spr.asm"
INCLUDE "data/scene/credits/cast_spr/newshotnan_spr.asm"
INCLUDE "data/scene/credits/cast_spr/yambow_spr.asm"
INCLUDE "data/scene/credits/cast_spr/hariharry_spr.asm"
INCLUDE "data/scene/credits/cast_spr/cannon_spr.asm"
INCLUDE "data/scene/credits/cast_spr/telly_spr.asm"
INCLUDE "data/scene/credits/cast_spr/unused_blocky_spr.asm"
INCLUDE "data/scene/credits/cast_spr/pipi_spr.asm"
INCLUDE "data/scene/credits/cast_spr/shotman_spr.asm"
INCLUDE "data/scene/credits/cast_spr/flyboy_spr.asm"
INCLUDE "data/scene/credits/cast_spr/springer_spr.asm"
INCLUDE "data/scene/credits/cast_spr/pierobot_spr.asm"
INCLUDE "data/scene/credits/cast_spr/mole_spr.asm"
INCLUDE "data/scene/credits/cast_spr/robbit_spr.asm"
INCLUDE "data/scene/credits/cast_spr/cook_spr.asm"
INCLUDE "data/scene/credits/cast_spr/batton_spr.asm"
INCLUDE "data/scene/credits/cast_spr/puchigoblin_spr.asm"
INCLUDE "data/scene/credits/cast_spr/scworm_spr.asm"
INCLUDE "data/scene/credits/cast_spr/matasaburo_spr.asm"
INCLUDE "data/scene/credits/cast_spr/kaminarigoro_spr.asm"
INCLUDE "data/scene/credits/cast_spr/crashman_spr.asm"
INCLUDE "data/scene/credits/cast_spr/metalman_spr.asm"
INCLUDE "data/scene/credits/cast_spr/woodman_spr.asm"
INCLUDE "data/scene/credits/cast_spr/airman_spr.asm"
INCLUDE "data/scene/credits/cast_spr/hardman_spr.asm"
INCLUDE "data/scene/credits/cast_spr/topman_spr.asm"
INCLUDE "data/scene/credits/cast_spr/magnetman_spr.asm"
INCLUDE "data/scene/credits/cast_spr/needleman_spr.asm"
INCLUDE "data/scene/credits/cast_spr/quint_spr.asm"

	mIncJunk "L016E46"