GFX_LvlTop: INCBIN "data/game/lvl/top/bg_gfx.bin"
GFX_LvlMagnet: INCBIN "data/game/lvl/magnet/bg_gfx.bin"
GFX_LvlNeedle: INCBIN "data/game/lvl/needle/bg_gfx.bin"
GFX_LvlCrash: INCBIN "data/game/lvl/crash/bg_gfx.bin"
GFX_LvlMetal: INCBIN "data/game/lvl/metal/bg_gfx.bin"
GFX_LvlWood: INCBIN "data/game/lvl/wood/bg_gfx.bin"
GFX_LvlAir: INCBIN "data/game/lvl/air/bg_gfx.bin"
GFX_LvlStation: INCBIN "data/game/lvl/station/bg_gfx.bin"
GFX_Title: INCBIN "data/title/title_gfx.bin"
GFX_Password: INCBIN "data/password/password_gfx.bin"
GFX_TitleDots: INCBIN "data/title/dots_gfx.bin"
GFX_TitleCursor: INCBIN "data/title/cursor_gfx.bin"
GFX_StageSel: INCBIN "data/stagesel/stagesel_gfx.bin"
GFX_Pause: INCBIN "data/game/pause_gfx.bin"
GFX_BgShared: INCBIN "data/game/sharedbg_gfx.bin"
	mIncJunk "L0A7D00"
GFX_Unused_HexFont: INCBIN "data/font/unused_hexfont_gfx.bin"
