GFX_WilyCastle: INCBIN "data/castle/wilycastle_gfx.bin"
GFX_WilyStation: INCBIN "data/space/wilystation_gfx.bin"
GFX_Space: INCBIN "data/space/space_gfx.bin"
GFX_SpaceOBJ: INCBIN "data/space/space_obj_gfx.bin"
GFX_HardMan: INCBIN "data/act/hardman/hardman_gfx.bin"
GFX_TopMan: INCBIN "data/act/topman/topman_gfx.bin"
