; Keys (as bit numbers)
DEF KEYB_A           EQU 0
DEF KEYB_B           EQU 1
DEF KEYB_SELECT      EQU 2
DEF KEYB_START       EQU 3
DEF KEYB_RIGHT       EQU 4
DEF KEYB_LEFT        EQU 5
DEF KEYB_UP          EQU 6
DEF KEYB_DOWN        EQU 7

; Keys (values)
DEF KEY_NONE         EQU 0
DEF KEY_A            EQU 1 << KEYB_A
DEF KEY_B            EQU 1 << KEYB_B
DEF KEY_SELECT       EQU 1 << KEYB_SELECT
DEF KEY_START        EQU 1 << KEYB_START
DEF KEY_RIGHT        EQU 1 << KEYB_RIGHT
DEF KEY_LEFT         EQU 1 << KEYB_LEFT
DEF KEY_UP           EQU 1 << KEYB_UP
DEF KEY_DOWN         EQU 1 << KEYB_DOWN


DEF GFXSET_TITLE       EQU $00 ; Title Screen
DEF GFXSET_STAGESEL    EQU $01 ; Stage Select
DEF GFXSET_PASSWORD    EQU $02 ; Password screen
DEF GFXSET_LEVEL       EQU $03 ; Level
DEF GFXSET_GETWPN      EQU $04 ; Get Weapon screen
DEF GFXSET_CASTLE      EQU $05 ; Wily Castle cutscene
DEF GFXSET_STATION     EQU $06 ; Wily Station cutscene
DEF GFXSET_GAMEOVER    EQU $07 ; Generic font (Game Over screen)
DEF GFXSET_SPACE       EQU $08 ; Space cutscenes (Wily Station, Ending)

DEF ACTGFX_PLAYER    EQU $00
DEF ACTGFX_SPACE1    EQU $01
DEF ACTGFX_02        EQU $02
DEF ACTGFX_03        EQU $03
DEF ACTGFX_04        EQU $04
DEF ACTGFX_05        EQU $05
DEF ACTGFX_MAGNETMAN EQU $06
DEF ACTGFX_07        EQU $07
DEF ACTGFX_NEEDLEMAN EQU $08
DEF ACTGFX_09        EQU $09
DEF ACTGFX_CRASHMAN  EQU $0A
DEF ACTGFX_0B        EQU $0B
DEF ACTGFX_METALMAN  EQU $0C
DEF ACTGFX_0D        EQU $0D
DEF ACTGFX_WOODMAN   EQU $0E
DEF ACTGFX_0F        EQU $0F
DEF ACTGFX_AIRMAN    EQU $10
DEF ACTGFX_11        EQU $11
DEF ACTGFX_12        EQU $12
DEF ACTGFX_13        EQU $13
DEF ACTGFX_HARDMAN   EQU $14
DEF ACTGFX_TOPMAN    EQU $15

DEF LVL_HARD           EQU $00
DEF LVL_TOP            EQU $01
DEF LVL_MAGNET         EQU $02
DEF LVL_NEEDLE         EQU $03
DEF LVL_CRASH          EQU $04
DEF LVL_METAL          EQU $05
DEF LVL_WOOD           EQU $06
DEF LVL_AIR            EQU $07
DEF LVL_CASTLE         EQU $08
DEF LVL_STATION        EQU $09

; wWpnUnlock0
DEF WPN_TP EQU %00000001
DEF WPN_AR EQU %00000010
DEF WPN_WD EQU %00000100
DEF WPN_ME EQU %00001000
DEF WPN_CR EQU %00010000
DEF WPN_NE EQU %00100000
DEF WPN_HA EQU %01000000
DEF WPN_MG EQU %10000000

; wWpnUnlock1
DEF WPN_RC EQU %00000001
DEF WPN_RM EQU %00000010
DEF WPN_RJ EQU %00000100
DEF WPN_SG EQU %00001000


DEF SECT_DISABLE     EQU $FF ; Magic value to disable the WINDOW layer and LYC trigger

DEF SCREVB_SCROLLV   EQU 7 ; Vertical scrolling
DEF SCREV_SCROLLV    EQU 1 << SCREVB_SCROLLV

DEF SCROLLV_UP       EQU 0
DEF SCROLLV_DOWN     EQU 1

; TilemapDef tilemap writing flags
DEF BGB_MVDOWN       EQU 6
DEF BGB_REPEAT       EQU 7
DEF BG_MVRIGHT       EQU $00
DEF BG_MVDOWN        EQU 1 << BGB_MVDOWN
DEF BG_NOREPEAT      EQU $00
DEF BG_REPEAT        EQU 1 << BGB_REPEAT

; wShutterEvMode
DEF SHUTTER_NONE     EQU $00
DEF SHUTTER_OPEN     EQU $01
DEF SHUTTER_CLOSE    EQU $02

DEF BLOCK_TILECOUNT_H    EQU $02 ; Number of 8x8 tiles in a block, horizontally
DEF BLOCK_TILECOUNT_V    EQU $02 ; Number of 8x8 tiles in a block, vertically

DEF LVLSCROLLV_BLOCKCOUNT  EQU $0C ; Number of blocks drawn when scrolling vertically

DEF SCREEN_GAME_BLOCKCOUNT_H EQU $0A ; Number of blocks horizontally in the game screen
DEF SCREEN_GAME_BLOCKCOUNT_V EQU $08 ; Number of blocks vertically in the game screen
DEF SCREEN_GAME_H          EQU SCREEN_GAME_BLOCKCOUNT_H * BLOCK_TILECOUNT_H * TILE_H ; $A0 ; Width, in pixels, of the gameplay screen
DEF SCREEN_GAME_V          EQU SCREEN_GAME_BLOCKCOUNT_V * BLOCK_TILECOUNT_V * TILE_V ; $80 ; Height, in pixels, of the gameplay screen


; Rooms
DEF COL_TILECOUNT_H  EQU $02 ; Number of tiles horizontally in a column
DEF ROOM_COLCOUNT    EQU $0A ; Number of columns in a room
DEF LVL_ROOMCOUNT    EQU 26 ; Max number of rooms in a level

DEF COL_PX_H         EQU COL_TILECOUNT_H * TILE_H ; $10 ; Width of a column, in pixels

DEF TILEID_SHUTTER_L EQU $78
DEF TILEID_SHUTTER_R EQU $79

; Gameplay
DEF BAR_MAX EQU $98 ; 152

DEF ACT_BOSS_START EQU $68
DEF ACT_HARDMAN    EQU $68
DEF ACT_TOPMAN     EQU $69
DEF ACT_MAGNETMAN  EQU $6A
DEF ACT_NEEDLEMAN  EQU $6B
DEF ACT_CRASHMAN   EQU $6C
DEF ACT_METALMAN   EQU $6D
DEF ACT_WOODMAN    EQU $6E
DEF ACT_AIRMAN     EQU $6F

DEF ACT_E0 EQU $E0
DEF ACT_E1 EQU $E1
DEF ACT_E2 EQU $E2
DEF ACT_E3 EQU $E3
DEF ACT_E4 EQU $E4

DEF ACTB_UNK_PROCFLAG EQU 7
DEF ACT_UNK_PROCFLAG EQU 1 << ACTB_UNK_PROCFLAG


; ??? AFG_ ? (ActorFlag)


; TODO: bits 3-5 influence the mapping frame

DEF ACTDIRB_UNK_UPGRAVEND EQU 6
DEF ACTDIRB_R EQU 7
DEF ACTDIR_UNK_UPGRAVEND EQU 1 << ACTDIRB_UNK_UPGRAVEND
DEF ACTDIR_L EQU $00
DEF ACTDIR_R EQU 1 << ACTDIRB_R

; Variants used for ActS_SetSprMapId

; Password dot locations
DEF iDotA1 EQU $00
DEF iDotA2 EQU $01
DEF iDotA3 EQU $02
DEF iDotA4 EQU $03
DEF iDotB1 EQU $04
DEF iDotB2 EQU $05
DEF iDotB3 EQU $06
DEF iDotB4 EQU $07
DEF iDotC1 EQU $08
DEF iDotC2 EQU $09
DEF iDotC3 EQU $0A
DEF iDotC4 EQU $0B
DEF iDotD1 EQU $0C
DEF iDotD2 EQU $0D
DEF iDotD3 EQU $0E
DEF iDotD4 EQU $0F

; Sound driver
DEF SND_MUTE              EQU $00

DEF BGM_TITLE             EQU $01
DEF BGM_STAGESELECT       EQU $02
DEF BGM_STAGESTART        EQU $03
DEF BGM_PASSWORD          EQU $04
DEF BGM_BOSS              EQU $05
DEF BGM_STAGECLEAR        EQU $06
DEF BGM_WEAPONGET         EQU $07
DEF BGM_CRASHMAN          EQU $08
DEF BGM_AIRMAN            EQU $09
DEF BGM_METALMAN          EQU $0A
DEF BGM_HARDMAN           EQU $0B
DEF BGM_WOODMAN           EQU $0C
DEF BGM_TOPMAN            EQU $0D
DEF BGM_MAGNETMAN         EQU $0E
DEF BGM_NEEDLEMAN         EQU $0F
DEF BGM_WILYINTRO         EQU $10
DEF BGM_WILYCASTLE        EQU $11
DEF BGM_ENDING            EQU $12
DEF BGM_UNUSEDENDING      EQU $13

DEF SFX_LAND              EQU $01
DEF SFX_SHOOT             EQU $02
DEF SFX_ENEMYHIT          EQU $03
DEF SFX_ENEMYDEAD         EQU $04
DEF SFX_DEFLECT           EQU $05
DEF SFX_EXPLODE           EQU $06
DEF SFX_BAR               EQU $07
DEF SFX_ETANK             EQU $08
DEF SFX_1UP               EQU $09
DEF SFX_SHUTTER           EQU $0A
DEF SFX_BOSSBAR           EQU $0B
DEF SFX_TELEPORTIN        EQU $0C
DEF SFX_TELEPORTOUT       EQU $0D
DEF SFX_UNKNOWN1          EQU $0E
DEF SFX_WEAPONABSORB      EQU $0F
DEF SFX_BLOCK             EQU $10
DEF SFX_UFOCRASH          EQU $11
DEF SFX_CURSORMOVE        EQU $12
DEF SFX_DAMAGED           EQU $13
DEF SFX_UNKNOWN2          EQU $14